#!/bin/sh
# {# jinja-parse #}

#
# Delayed reboot helper script used by DM
#

[ $# -ne 1 ] && exit 1

/bin/sleep $1
{% if CONFIG_OSP_REBOOT_CLI_OVERRIDE -%}
/sbin/reboot -Rtype=cloud -Rreason=delayed-reboot
{%- else -%}
/sbin/reboot
{%- endif %}
